### ISSUE TITLE
Episodes not Updating

### ISSUE THREAD

**Issue by IoGza** [lolamtisch/MALSync#106] opened 2019-06-08 06:14 UTC
This has been happening for a couple of weeks or so, but as I use KissAnime I found that whenever I move on to the next episode that the bar on the bottom of the page that shows up in order to keep track of an episode is in a perpetual refresh state. Because of this, the episode number for shows I watch are not reflected in my MAL and I have to manually press the "Update MAL to Ep__," or go into MAL and do it myself rather than it doing so automatically.

**Additional information:**
 - Browser: Chrome
 - Type: Extension

**Comment by lolamtisch** [comment] 2019-06-08 08:26
perpetual refresh state -> That means he is not able to find an running video player. What server are you watching on. Could be that it is a new one that I have not in the list (Flash player is not supported).

 
You can switch the sync mode to instant, so it updates the list directly without checking for the video and waiting until 80% are watched.
![image](https://user-images.githubusercontent.com/12599334/59144278-de2c5f00-89d5-11e9-8ec7-3610bb425abf.png)

**Comment by lolamtisch** [comment] 2019-06-21 18:36
Closing for now.
You can reopen it if the problem is not solved.

**Closed by lolamtisch** 2019-06-21 18:36 UTC
Labels: more info needed

**Comment by Ayushk222** [comment] 2021-05-22 18:14
I have the same issue. The bottom popup seems to have the progress bar running indefinitely. This is happening on 9anime.to, gogoanime.ai, animixplay.to. I have tried different browsers namely Vivaldi, Chrome, OperaGX, Edge (Chromium) and Firefox. I have to update manually all the time.

**Comment by lolamtisch** [comment] 2021-05-23 18:07
@Ayushk222 Use another video player or wait for the next release.

**Comment by Ayushk222** [comment] 2021-05-23 19:57
@lolamtisch Just to give a little more insight on the issue. So the issue I found here is that it works sometimes and sometimes it doesn't on 9anime.to and gogoanime.ai on animixplay.to it works fine on the gogostream but not on others. Maybe it's a problem on my end? Anyways, sorry for posting in a closed issue as I didn't want to make a thread for an identical issue.

**Comment by lolamtisch** [comment] 2021-05-23 20:02
@Ayushk222 
Try this. It is because the player does not get recognized. This should fix 9anime it think
![image](https://user-images.githubusercontent.com/12599334/119274899-84e58680-bc12-11eb-84ba-711ad1020022.png)

**Comment by Ayushk222** [comment] 2021-05-24 03:27
@lolamtisch Yup it fixed 9anime.to. Thanks!

**Comment by Key-explanation** [comment] 2022-04-08 12:27
I am having the same problem. i am running malsync script on Tampermonkey because the extension is crashing my browser. the episodes doesn't update normally and i have to update it manually. the "Custom Domain" option isn't avaliable.

**Comment by bbeenn1** [comment] 2022-04-13 21:02
These are in the userscript for Tampermonkey already (to the best of my knowledge it is lines 433 and 434 that would allow the match)
`// @match *://vidstreamz.online/embed/*
// @match *://vidstream.pro/embed/*`

I am experiencing the same issue on 9anime.id for vidstream of it not recognizing the video player - it worked just fine on 9anime.center and 9anime.to until recently (uncertain when since the last show I watched I was basically forced to use mycloud)

**Comment by henrik9999** [comment] 2022-04-13 21:22
This is an old issue the Domains that have been listed here before have been long added to malsync since then. Wait for the next release for missing domains to be added. Report broken videos with a new issue or on the discord. Userscript does not support custom domains unless you understand how to edit the script.
