### ISSUE TITLE
Wrong episode numbers from Crunchyroll

### ISSUE THREAD

**Issue by NekoLulu** [lolamtisch/MALSync#27] opened 2018-12-03 12:47 UTC
**Describe the bug**
Crunchyroll sometimes counts episodes of big series in one sequence for many cours. MALSync always uses that episode number to mark the watched episode, e.g., watched 63 out of 12, setting 12 episodes watched and the cour completed even after the first episode. It's inconvenient to disable MALSync while watching such series and you can't edit history on MAL much. Can you at least make MALSyn recognize episodes numbers that are off and not set wrong numbers? May MALSync can be made to ask for a number, or, count them from 1, if none have been watched yet, or, recognize an episode in MAL videos. 

**Steps to reproduce the behavior:**
Start watching Gintama.: Shirogane no Tamashii-hen - Kouhan-sen, MALSync will display a message that
Episode: 317/14 have been marked, even if you click "Undo" it still leaves episode 14 as watched in MAL history.

**Additional information:**
 - Browser: Google Chrome Version 70.0.3538.110 (Official Build) (64-bit)
 - Type: Extension
 - Url: https://www.crunchyroll.com/gintama/episode-204-use-a-calligraphy-pen-for-new-years-cardsthe-heart-comes-before-chocolate-573200

**Comment by lolamtisch** [comment] 2018-12-03 13:34
@NekoLulu 
Please take a look at "The Series uses an episode offset", it shows how you can set a episode offset, making it possible to recognize episode 317 as ep 1. The offset should be `-316`.
https://github.com/lolamtisch/MALSync/wiki/Troubleshooting#the-series-uses-an-episode-offset

Some other tipps:
- Leave the field 'MyAnimeList Url' empty in miniMAL will disable tracking for that entry, but please dont sent a database correction request then (click cancel on popup). (MyAnimeEntry entry is not correct) https://github.com/lolamtisch/MALSync/wiki/Troubleshooting#myanimeentry-entry-is-not-correct

- If "Autotracking" is disabled in miniMAL, it will always ask you before updating the entry.
![image](https://user-images.githubusercontent.com/12599334/49376502-c1059380-f707-11e8-819e-aa8aacb9c7cd.png)

This is kind of a duplicate of Issue #18. Could you cloese the Issue if you have no futher questions

**Comment by lolamtisch** [comment] 2018-12-03 13:44
And you can edit MALs history. Atleast remove it from the history is possible. There is a link on your profile page "Anime History" were you can delete them.

**Comment by NekoLulu** [comment] 2018-12-03 13:50
Thanks for the workarounds. Hopefully, full solution will be developed later. Also, on MAL a deleted from history episode doesn't show up if you watch it again.

**Closed** 2018-12-03 13:50 UTC
Labels: duplicate, good first issue
