### ISSUE TITLE
Give us to option to disable the skip the opening and jump back shortcuts

### ISSUE THREAD

**Issue by varemenos** [lolamtisch/MALSync#137] opened 2019-07-13 21:32 UTC
You are currently overriding the ctrl + left/right shortcuts which are utilized by shortcuts provided by the system, which among other things also moves the cursor word-word when editing text.

Could you please give us an option to disable this as it makes it really hard to edit text? (I'm not even able to perform this shortcut in the URL/location bar and the chrome Devtools, which is kind of absurd as the shortcut should at least be contained to the website itself.

Not sure if I should have filed this as a bug or a feature request, it depends on how you see it I guess.

![image](https://user-images.githubusercontent.com/626343/61176720-11aa6c80-a5c6-11e9-9ae9-c3e17577983e.png)

**Comment by lolamtisch** [comment] 2019-07-13 21:36
Duplicate of #67

That shortcut is already disabled by default. How to remove/change it is describt here:
https://github.com/lolamtisch/MALSync/wiki/Shortcuts

**Closed** 2019-07-14 16:38 UTC
Labels: duplicate
